import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/_component/header/FirstHeader";
import SecondaryHeader from "@/_component/header/SecondHeader";

const montserrat = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link href="https://fonts.googleapis.com/css2?family=Luckiest+Guy&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${montserrat.variable}`}
      >
        <div className="w-full max-w-[1700px] mx-auto overflow-hidden">
          <Header />
          <SecondaryHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
